from .simpleFCs_v1 import simpleFCs_v1
from .simpleFCs_v1d import simpleFCs_v1d
from .simpleFCs_v2 import simpleFCs_v2
from .simpleFCs_v2d import simpleFCs_v2d
from .ABMIL import ABMIL
from .ABMIL_v2 import ABMIL_v2
from .TransMIL import TransMIL
from .TransMIL_per_modality import TransMIL_per_modality
from .CLIP import CLIP